import type { RegionId } from "@/data/regions";

/**
 * Placeholder capsule-and-sphere humanoid (PLANNING.md §6 build order rule:
 * validate raycast selection, confirm loop, and pins against a placeholder
 * segmented figure BEFORE investing in the real mesh).
 *
 * Each region is one primitive mesh keyed to a region ID. Coordinates:
 * y up, ground at y=0, figure faces +z (toward the default camera), so
 * anatomical left = +x. Positions double as pin anchors (region centroids).
 */
export interface RegionMeshSpec {
  kind: "sphere" | "capsule";
  position: readonly [number, number, number];
  radius: number;
  /** capsule mid-section length */
  length?: number;
  /** non-uniform scale for flattened torso panels and feet */
  scale?: readonly [number, number, number];
}

/*
 * Proxy volumes are sized to sit INSIDE the placeholder body silhouette
 * (generated by scripts/make-placeholder-body.mjs) so the selection overlay,
 * inflated along normals, always clears the skin from outside rather than
 * peeking out of it. Numbers derived from the blob part dimensions in that
 * script.
 */
export const FIGURE: Record<RegionId, RegionMeshSpec> = {
  head: { kind: "sphere", position: [0, 3.28, 0], radius: 0.29 },
  "neck.front": { kind: "capsule", position: [0, 2.92, 0.04], radius: 0.075, length: 0.14 },
  "neck.back": { kind: "capsule", position: [0, 2.92, -0.04], radius: 0.075, length: 0.14 },
  "torso.chest.left.anterior": {
    kind: "sphere", position: [0.19, 2.5, 0.12], radius: 0.3, scale: [0.75, 0.95, 0.45],
  },
  "torso.chest.right.anterior": {
    kind: "sphere", position: [-0.19, 2.5, 0.12], radius: 0.3, scale: [0.75, 0.95, 0.45],
  },
  "torso.chest.breast.left": { kind: "sphere", position: [0.17, 2.4, 0.1], radius: 0.11 },
  "torso.chest.breast.right": { kind: "sphere", position: [-0.17, 2.4, 0.1], radius: 0.11 },
  "torso.abdomen.anterior": {
    kind: "sphere", position: [0, 1.98, 0.1], radius: 0.32, scale: [1.1, 0.8, 0.42],
  },
  "torso.pelvis.anterior": {
    kind: "sphere", position: [0, 1.54, 0.08], radius: 0.24, scale: [0.9, 0.5, 0.35],
  },
  "torso.back.upper": {
    kind: "sphere", position: [0, 2.5, -0.12], radius: 0.32, scale: [1.25, 0.9, 0.42],
  },
  "torso.back.lower": {
    kind: "sphere", position: [0, 1.98, -0.12], radius: 0.32, scale: [1.1, 0.8, 0.42],
  },
  "shoulder.left": { kind: "sphere", position: [0.45, 2.7, 0], radius: 0.12 },
  "shoulder.right": { kind: "sphere", position: [-0.45, 2.7, 0], radius: 0.12 },
  "arm.left": { kind: "capsule", position: [0.55, 2.05, 0], radius: 0.09, length: 0.85 },
  "arm.right": { kind: "capsule", position: [-0.55, 2.05, 0], radius: 0.09, length: 0.85 },
  "hand.left": { kind: "sphere", position: [0.57, 1.46, 0], radius: 0.09 },
  "hand.right": { kind: "sphere", position: [-0.57, 1.46, 0], radius: 0.09 },
  "hip.left": { kind: "sphere", position: [0.2, 1.6, 0], radius: 0.16, scale: [1, 0.9, 1.4] },
  "hip.right": { kind: "sphere", position: [-0.2, 1.6, 0], radius: 0.16, scale: [1, 0.9, 1.4] },
  "leg.upper.left": { kind: "capsule", position: [0.2, 1.18, 0], radius: 0.115, length: 0.4 },
  "leg.upper.right": { kind: "capsule", position: [-0.2, 1.18, 0], radius: 0.115, length: 0.4 },
  "leg.lower.left": { kind: "capsule", position: [0.2, 0.55, 0], radius: 0.105, length: 0.5 },
  "leg.lower.right": { kind: "capsule", position: [-0.2, 0.55, 0], radius: 0.105, length: 0.5 },
  "foot.left": {
    kind: "sphere", position: [0.2, 0.09, 0.08], radius: 0.115, scale: [0.8, 0.55, 1.4],
  },
  "foot.right": {
    kind: "sphere", position: [-0.2, 0.09, 0.08], radius: 0.115, scale: [0.8, 0.55, 1.4],
  },
};

export function regionCentroid(id: RegionId): readonly [number, number, number] {
  return FIGURE[id].position;
}
