import type { RegionId } from "@/data/regions";

/**
 * Placeholder capsule-and-sphere humanoid (PLANNING.md §6 build order rule:
 * validate raycast selection, confirm loop, and pins against a placeholder
 * segmented figure BEFORE investing in the real mesh).
 *
 * Each region is one primitive mesh keyed to a region ID. Coordinates:
 * y up, ground at y=0, figure faces +z (toward the default camera), so
 * anatomical left = +x. Positions double as pin anchors (region centroids).
 */
export interface RegionMeshSpec {
  kind: "sphere" | "capsule";
  position: readonly [number, number, number];
  radius: number;
  /** capsule mid-section length */
  length?: number;
  /** non-uniform scale for flattened torso panels and feet */
  scale?: readonly [number, number, number];
}

/*
 * Proxy volumes are sized to sit INSIDE the placeholder body silhouette
 * (generated by scripts/make-placeholder-body.mjs) so the selection overlay,
 * inflated along normals, always clears the skin from outside rather than
 * peeking out of it. Numbers derived from the blob part dimensions in that
 * script.
 */
export const FIGURE: Record<RegionId, RegionMeshSpec> = {
  head: { kind: "sphere", position: [0, 3.28, 0], radius: 0.29 },
  "head.ear.left": { kind: "sphere", position: [0.24, 3.28, 0], radius: 0.06 },
  "head.ear.right": { kind: "sphere", position: [-0.24, 3.28, 0], radius: 0.06 },
  "head.eyes": {
    kind: "sphere", position: [0, 3.32, 0.24], radius: 0.09, scale: [1.6, 0.6, 0.6],
  },
  "head.jaw": {
    kind: "sphere", position: [0, 3.08, 0.14], radius: 0.1, scale: [1.4, 0.6, 0.9],
  },
  "neck.front": { kind: "capsule", position: [0, 2.92, 0.04], radius: 0.075, length: 0.14 },
  "neck.back": { kind: "capsule", position: [0, 2.92, -0.04], radius: 0.075, length: 0.14 },
  // Chest panels overlap across the midline and reach the neck so no
  // front-facing ray can slip between them to a back proxy (sternum-notch
  // gap caused front taps to resolve to "Upper back").
  "torso.chest.left.anterior": {
    kind: "sphere", position: [0.15, 2.5, 0.12], radius: 0.3, scale: [0.8, 1.1, 0.45],
  },
  "torso.chest.right.anterior": {
    kind: "sphere", position: [-0.15, 2.5, 0.12], radius: 0.3, scale: [0.8, 1.1, 0.45],
  },
  // Breast proxies must protrude past the chest panels' front surface
  // (z 0.26 > chest 0.255) or the chest always wins the raycast.
  "torso.chest.breast.left": { kind: "sphere", position: [0.16, 2.38, 0.17], radius: 0.09 },
  "torso.chest.breast.right": { kind: "sphere", position: [-0.16, 2.38, 0.17], radius: 0.09 },
  "torso.abdomen.upper.anterior": {
    kind: "sphere", position: [0, 2.1, 0.1], radius: 0.3, scale: [1.3, 0.6, 0.45],
  },
  "torso.abdomen.lower.anterior": {
    kind: "sphere", position: [0, 1.78, 0.1], radius: 0.3, scale: [1.3, 0.6, 0.45],
  },
  "torso.pelvis.anterior": {
    kind: "sphere", position: [0, 1.54, 0.08], radius: 0.24, scale: [0.9, 0.5, 0.35],
  },
  "torso.groin": {
    kind: "sphere", position: [0, 1.43, 0.05], radius: 0.1, scale: [0.8, 0.5, 0.5],
  },
  // Back panels are clamped entirely into the back half (max z ≈ -0.002)
  // so they can never catch a ray that slipped past the front proxies.
  "torso.back.upper": {
    kind: "sphere", position: [0, 2.5, -0.13], radius: 0.32, scale: [1.2, 0.9, 0.4],
  },
  "torso.back.lower": {
    kind: "sphere", position: [0, 1.98, -0.13], radius: 0.32, scale: [1.05, 0.8, 0.4],
  },
  "shoulder.left": { kind: "sphere", position: [0.45, 2.7, 0], radius: 0.12 },
  "shoulder.right": { kind: "sphere", position: [-0.45, 2.7, 0], radius: 0.12 },
  "arm.upper.left": { kind: "capsule", position: [0.55, 2.3, 0], radius: 0.085, length: 0.35 },
  "arm.upper.right": { kind: "capsule", position: [-0.55, 2.3, 0], radius: 0.085, length: 0.35 },
  "arm.elbow.left": { kind: "sphere", position: [0.55, 2.05, 0], radius: 0.088 },
  "arm.elbow.right": { kind: "sphere", position: [-0.55, 2.05, 0], radius: 0.088 },
  "arm.fore.left": { kind: "capsule", position: [0.55, 1.8, 0], radius: 0.08, length: 0.3 },
  "arm.fore.right": { kind: "capsule", position: [-0.55, 1.8, 0], radius: 0.08, length: 0.3 },
  "arm.wrist.left": { kind: "sphere", position: [0.55, 1.57, 0], radius: 0.08 },
  "arm.wrist.right": { kind: "sphere", position: [-0.55, 1.57, 0], radius: 0.08 },
  "hand.left": { kind: "sphere", position: [0.57, 1.48, 0], radius: 0.08 },
  "hand.right": { kind: "sphere", position: [-0.57, 1.48, 0], radius: 0.08 },
  "hand.fingers.left": {
    kind: "sphere", position: [0.57, 1.38, 0], radius: 0.05, scale: [1.2, 1, 1],
  },
  "hand.fingers.right": {
    kind: "sphere", position: [-0.57, 1.38, 0], radius: 0.05, scale: [1.2, 1, 1],
  },
  "hip.left": { kind: "sphere", position: [0.2, 1.6, 0], radius: 0.16, scale: [1, 0.9, 1.4] },
  "hip.right": { kind: "sphere", position: [-0.2, 1.6, 0], radius: 0.16, scale: [1, 0.9, 1.4] },
  "leg.upper.left": { kind: "capsule", position: [0.2, 1.15, 0], radius: 0.115, length: 0.35 },
  "leg.upper.right": { kind: "capsule", position: [-0.2, 1.15, 0], radius: 0.115, length: 0.35 },
  "leg.knee.left": { kind: "sphere", position: [0.2, 0.9, 0], radius: 0.11 },
  "leg.knee.right": { kind: "sphere", position: [-0.2, 0.9, 0], radius: 0.11 },
  // calf = back of the lower leg, shin = front; split on z
  "leg.calf.left": { kind: "capsule", position: [0.2, 0.62, -0.035], radius: 0.09, length: 0.3 },
  "leg.calf.right": { kind: "capsule", position: [-0.2, 0.62, -0.035], radius: 0.09, length: 0.3 },
  "leg.shin.left": { kind: "capsule", position: [0.2, 0.62, 0.035], radius: 0.09, length: 0.3 },
  "leg.shin.right": { kind: "capsule", position: [-0.2, 0.62, 0.035], radius: 0.09, length: 0.3 },
  "leg.ankle.left": { kind: "sphere", position: [0.2, 0.33, 0], radius: 0.09 },
  "leg.ankle.right": { kind: "sphere", position: [-0.2, 0.33, 0], radius: 0.09 },
  "foot.left": {
    kind: "sphere", position: [0.2, 0.09, 0.08], radius: 0.115, scale: [0.8, 0.55, 1.4],
  },
  "foot.right": {
    kind: "sphere", position: [-0.2, 0.09, 0.08], radius: 0.115, scale: [0.8, 0.55, 1.4],
  },
  "foot.toes.left": {
    kind: "sphere", position: [0.2, 0.07, 0.2], radius: 0.055, scale: [1.3, 0.75, 1],
  },
  "foot.toes.right": {
    kind: "sphere", position: [-0.2, 0.07, 0.2], radius: 0.055, scale: [1.3, 0.75, 1],
  },
};

export function regionCentroid(id: RegionId): readonly [number, number, number] {
  return FIGURE[id].position;
}
